### ISSUE TITLE
Problems in metrics

### ISSUE THREAD

**Issue by btaille** [datquocnguyen/jointRE#2]
Hello,

I think there are two issues with your metrics that prevent comparison with state-of-the-art:

1. In your paper, you write about **macro-averaged** F1 which indeed seems to be what you use in your code. Almost every work in NER or RE use **micro-averaged** F1 score.

2. You discard the "Other" entity type. As far as I understand in (Bekoulis 2018), this is only done with Entity Classification (i.e. your Setup 2) and not joint NER and RE.

**Comment by datquocnguyen** [comment]
Hello,
1. I followed Adel and Schutze (2017) to use macro-averaged F1, so that I could compare with their scores (You can ask them why they did not use micro-averaged F1). In addition, Bekoulis et al. (2018) also used  [macro-averaged F1](https://github.com/bekou/multihead_joint_entity_relation_extraction/blob/76f152175420680742f6a77bdd2ed8fa6a5b2013/tf_utils.py). 
2. I also followed Adel and Schutze (2017) to discard the "Other" entity type. I think Bekoulis et al. (2018)  also discarded the "Other" entity type as [here](https://github.com/bekou/multihead_joint_entity_relation_extraction/blob/76f152175420680742f6a77bdd2ed8fa6a5b2013/tf_utils.py#L77).

**Comment by btaille** [comment]
Thanks for your answer,

You are right, in setup 2 both (Adel and Schutze 2017) and (Bekoulis 2018) use macro F1, I was not aware of that.

But in setup 1 which is the true end-to-end RE, (Bekoulis 2018) and previous works use micro-F1 score.
The lines you point to are after `if self.config.evaluation_method == "relaxed":`  which corresponds to your setup 2.

Otherwise he uses `getChunkedOverallF1()` from [eval.py](https://raw.githubusercontent.com/bekou/multihead_joint_entity_relation_extraction/76f152175420680742f6a77bdd2ed8fa6a5b2013/eval.py) and you can see that it is micro-average and that "Other" is not discarded.

I agree that all these different settings are confusing but it is necessary to ensure that the comparisons are valid.

**Comment by datquocnguyen** [comment]
[Bekoulis et al. (2018)'s paper](https://aclweb.org/anthology/D18-1307)  did not clarify which F1 (micro/macro) they used. As they used Adel and Schutze (2017)'s data, I assumed they followed the macro-averaged metric used in Adel and Schutze (2017) for both setups. 

Regarding Setup 1, if you think Bekoulis et al. (2018) used micro-averaged F1, you can compare to Bekoulis et al. (2018) w.r.t. micro-averaged F1. Also, you can additionally compute your macro-averaged F1 in comparison to jointER.

I believe that whatever metric used for Setup 1 does not affect the conclusion and contributions of our paper. We still obtain SOTA performance under Setup 2 which is used in most previous work on CoNLL04.
