### ISSUE TITLE
Invalid gradient occurs during training at later epochs

### ISSUE THREAD

**Issue by zwelz3** [datquocnguyen/jointRE#7]
I'm noticing that the training routine can fail due to NaN gradient values occasionally. 

```python
Starting epoch 91
Processing sentence number: 100 , Loss: 0.0293 , Time: 12.89
Processing sentence number: 200 , Loss: 0.0100 , Time: 14.91
Traceback (most recent call last):
  File "jNERE.py", line 83, in <module>
    parser.Train(train_data, train_id2nerBILOU, id2arg2rel)
  File ".../jointRE/jNERE/learner.py", line 449, in Train
    self.trainer.update()
  File "_dynet.pyx", line 5728, in _dynet.Trainer.update
  File "_dynet.pyx", line 5733, in _dynet.Trainer.update
RuntimeError: Magnitude of gradient is bad: -nan
```

**Comment by datquocnguyen** [comment]
I do not really know what happened. It may be because of your DyNet but I am not sure. 
BTW, how many epochs does the model run to converge? 
In my paper's experiments, the model likely converges after 50-70 epochs. Thus though the training rountine might fail at epoch 91th, it does not really affect the model performance.

**Comment by zwelz3** [comment]
I installed the version of dynet specified. It appeared to have converged, but the included script runs for 100 epochs.
